version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minio-net

  minio1: &minio-common
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio1
    hostname: minio1
    volumes:
      - minio1-data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
      MINIO_PROMETHEUS_URL: "http://prometheus:9090"
      MINIO_PROMETHEUS_JOB_ID: "minio-job"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_DRIVE_MAX_TIMEOUT: 10s
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio2:
    <<: *minio-common
    container_name: minio2
    hostname: minio2
    volumes:
      - minio2-data:/data
    ports:
      - "9002:9001"

  minio3:
    <<: *minio-common
    container_name: minio3
    hostname: minio3
    cap_add:
      - NET_ADMIN
    volumes:
      - minio3-data:/data
    ports:
      - "9003:9001"

  minio4:
    <<: *minio-common
    container_name: minio4
    hostname: minio4
    volumes:
      - minio4-data:/data
    ports:
      - "9004:9001"

  minio5:
    <<: *minio-common
    container_name: minio5
    hostname: minio5
    volumes:
      - minio5-data:/data
    ports:
      - "9005:9001"

  minio6:
    <<: *minio-common
    container_name: minio6
    hostname: minio6
    volumes:
      - minio6-data:/data
    ports:
      - "9006:9001"

networks:
  minio-net:
    driver: bridge

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  minio5-data:
  minio6-data: