global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'minio-job'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio1:9000', 'minio2:9000', 'minio3:9000', 'minio4:9000', 'minio5:9000', 'minio6:9000']