version: '3.8'

services:
  minio1:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio1
    hostname: minio1
    volumes:
      - minio1-data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio2:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio2
    hostname: minio2
    volumes:
      - minio2-data:/data
    ports:
      - "9002:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio3:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio3
    hostname: minio3
    volumes:
      - minio3-data:/data
    ports:
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio4:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio4
    hostname: minio4
    volumes:
      - minio4-data:/data
    ports:
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio5:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio5
    hostname: minio5
    volumes:
      - minio5-data:/data
    ports:
      - "9005:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

  minio6:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio6
    hostname: minio6
    volumes:
      - minio6-data:/data
    ports:
      - "9006:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
      MINIO_STORAGE_CLASS_STANDARD: "EC:2"
    command: server http://minio{1...6}/data --console-address ":9001"
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  minio5-data:
  minio6-data: